### ISSUE TITLE
4.12.4 - Does not start playback until audio device switched

### ISSUE THREAD

**Issue by 4oo4** [flathub/com.plexamp.Plexamp#270]
I’ve started experiencing a weird issue with the Plexamp flatpak on Linux sometime after upgrading to 4.12.4. Basically when I launch the app and first try to play a song, there’s no audio output and the playback seekbar will keep skipping backwards/forwards by 1 second.

The only way I can fix this is to go into the settings and change the audio device and then back to Pulseaudio, but I have to do this every time I open the app. I’ve had this happen on two different Linux desktops, one Debian 12 and the other Debian 13. No other applications besides Plexamp have any issues like this. I cleared out its data folder under `~/.var`, and that fixed it exactly one time, but then after closing/reopening the app it starts doing it again.

As soon as I downgrade to 4.12.3 the issue goes away. I can also reproduce it with the 4.12.4 appimage.

**Comment by dezza** [comment]
Have you tried keeping it on PulseAudio ?

Flatpak can only communicate with PulseAudio afaik and this might actually be the issue.

I agree its not optimal. I will look into forcing it to PulseAudio if this indeed fixes it - because this has been puzzling me for quite some time.. I just now noticed that if you start a different playback (say youtube in a browser) then Plexamp will refuse to play in locked state.

I think this might be it..

**Comment by ctrlaltjakub** [comment]
I have the same issue, tried  to keep it on default or on pipewire sound serer (which i believe is pulseaudio) and it doesnt help. 
I do not have to start another playback to cause the issue. Simple app restart is enough. 
Edit: Im on Fedora 42

**Comment by dezza** [comment]
As previously stated it NEEDS to be PulseAudio in flatpak, because Flatpak does not have access to PipeWire, its only showing - but I bet its a dummy redirect to PulseAudio..

**Comment by ctrlaltjakub** [comment]
it doesnt show puleaudio in options in plexamp

**Comment by dezza** [comment]
```console
dza:~ $ flatpak info --show-permissions com.plexamp.Plexamp 
[Context]
shared=network;ipc;
# Verify pulseaudio here..
sockets=wayland;pulseaudio;
devices=dri;
filesystems=

[Session Bus Policy]
org.mpris.MediaPlayer2.Plexamp=own

[Environment]
DISPLAY=:0
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons

```

**Comment by 4oo4** [comment]
@dezza Yes I always kept it on either Pulseaudio or default (which I believe should also point to Pulseaudio), but playback wouldn't start until I switched it to a different output device and back to Pulseaudio.

**Comment by NotCassim** [comment]
I have the same issue and it's driving me crazy.

**Comment by Rollbacke** [comment]
I also confirmed this on Manjaro with PipeWire.
I tested the AppImage and Flatpak, and found the same problem.

**Comment by thob** [comment]
same here on Pop!_OS, 

```
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=dri;

[Session Bus Policy]
org.mpris.MediaPlayer2.Plexamp=own

```

**Comment by stadsport** [comment]
Same issue on Fedora 42 on two machines. It popped up a few months ago, and it was fairly intermittent at first, but now it's pretty constant. My desktop has even interrupted playback and I had to go into Plexamp's settings and switch/switch back the output device.

I don't think setting it to PulseAudio is the solution either (though I haven't tried it yet, doing so now). If left on "Default" it should follow the OS's default output device, which it normally does and used to do.

**Comment by roseyhead** [comment]
I don't know if this is the same issue but my Plexamp often won't play when I open it, I was changing the sound device too but I found that just closing and reopening Plexamp 2-5 times fixes it. Open Plexamp > click Play > nothing happens > close Plexamp > repeat until Play starts playing. I find this a lot easier than going into the settings and changing the sound device. Same behaviour whether I have Pulse or Pipewire set as output.

**Comment by rob-sve** [comment]
I've found that if I play something in another application (like a youtube video in Firefox), then start playback in Plexamp, it also starts working normally after that. Using the Appimage version.

**Comment by Rollbacke** [comment]
> I don't know if this is the same issue but my Plexamp often won't play when I open it, I was changing the sound device too but I found that just closing and reopening Plexamp 2-5 times fixes it. Open Plexamp > click Play > nothing happens > close Plexamp > repeat until Play starts playing. I find this a lot easier than going into the settings and changing the sound device. Same behaviour whether I have Pulse or Pipewire set as output.

I did this at first (closing and open until it worked, it ended up tiring me out and I almost went back to using the legacy Plex).
Finally, I switched between "Default" and the sound card name. When one didn't work, I switched to the other, and it usually worked.

Also, I strongly recommend duplicate what you said here on the Plex forum thread to get a reaction from Plex dev: https://forums.plex.tv/t/plexamp-flatpak-appimage-does-not-start-playback-until-audio-device-switched/929631

**Comment by Rollbacke** [comment]
-It seems fixed in version 4.13.0-

Edit: Nope... False joy...

**Comment by 4oo4** [comment]
Can confirm, I had to switch it back one last time but after that I didn't have to after installing 4.13.0

**Comment by trankillity** [comment]
4.13.0 is [not available](https://flathub.org/en/apps/com.plexamp.Plexamp) on Flathub. Did it get rolled back for some reason?

**Comment by 4oo4** [comment]
It may have. I just noticed that I still have the issue again after a reboot, so I'm reopening the issue.

**Comment by Rollbacke** [comment]
Can confirm. Issue still here.
I think the cache simply reset itself on the first launch after 4.13.0 upgrade.
I had the impression that it worked well more than once, but now I have the problem every time I launch it.
Besides, I have the problem on Gnome or KDE, so it's probably related to PipeWire/PA.

**Comment by ossimark** [comment]
Same issue here on 4.12.4. Missed the upgrade to 4.13.0, can't test that (Flathub).

**Comment by XenonPK** [comment]
I ended up rolling back to 4.12.3 for now, until this gets fixed.
In case anyone needs it here is how I did it:

```
sudo flatpak update \
  --commit=$(flatpak remote-info --log flathub com.plexamp.Plexamp | grep -B1 -F 'to 4.12.3' | sed -e 's/^ \+Commit: \+//' -e 1q) \
  com.plexamp.Plexamp
```

This prevents further updates to this flatpak:
```
flatpak mask com.plexamp.Plexamp
```

**Comment by paramoNNNN** [comment]
I don't think it's directly related to flathub as I'm facing the same issue on NixOS and ended up rolling back to 4.12.3.

flake.nix
```nix
    plexamp.url =
      "nixpkgs/e6f23dc08d3624daab7094b701aa3954923c6bbb"; # 4.12.3
```

configuration.nix
```nix
{ pkgs, inputs, ... }:
let
  plexampPkgs = import inputs.plexamp {
    system = pkgs.system;
    config.allowUnfree = true;
  };
in {
  environment.systemPackages = with pkgs; [
    plexampPkgs.plexamp
  ];
};
```

**Comment by emenel** [comment]
same here on nixos

**Comment by hermannx5** [comment]
I have the same issue on Ubuntu 25.10 and reverted back to 4.12.3.

**Comment by agentgodzilla** [comment]
Can confirm its unrelated to flatpak

I have this issue on EndeavourOS with https://aur.archlinux.org/packages/plexamp-appimage

**Comment by thennothinghappened** [comment]
I'm also seeing this w/o flatpak; it's a plexamp issue. In my case it seems to interact poorly with EasyEffects, and its a 1/10 dice roll each reboot of plexamp whether it'll play audio, or skip back and forth the same one-second region silently.

**Comment by penchochris** [comment]
Same problem with CachyOS, installing it with yay, package name: plexamp-bin

**Comment by quelixir** [comment]
Exact same issue on Fedora 43.

Here's my `$ flatpak info --show-permissions com.plexamp.Plexamp` output:

```
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=dri;

[Session Bus Policy]
org.mpris.MediaPlayer2.Plexamp=own
```

I downgraded to 4.12.3 per the suggested command from @XenonPK (thanks!), and audio's now working fine with no issues.

**Comment by rollecode** [comment]
Just noticed this with plexamp-appimage-4.13.0-2 and plexamp-bin-4.13.0-1 on Arch Linux. 4.12.3 confirmed working.

**Comment by penchochris** [comment]
> Just noticed this with plexamp-appimage-4.13.0-2 and plexamp-bin-4.13.0-1 on Arch Linux. 4.12.3 confirmed working.

This just helped me to find this solution:

1. Install plexamp from flatpak
flatpak install flathub com.plexamp.Plexamp 

2. Change to version 4.12.3
flatpak update --commit=18d4b702fd1a05785d773b53cc995869a26b06228b7adb73cf8f197525aecf71 com.plexamp.Plexamp

3. Block updates till fixed:
flatpak mask com.plexamp.Plexamp

**Comment by aubrey-wodonga** [comment]
Marking as closed.  This was fixed in the latest [Plexamp release](https://forums.plex.tv/t/plexamp-release-notes/221280/85). In future, please raise issues via the Plex Forums. This repository is mostly unmonitored.
